# Generated by Django 3.1.12 on 2021-06-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='projects_pr_name_11d782_idx'),
        ),
    ]
