# Generated by Django 3.1.12 on 2021-06-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state_changed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
