# Generated by Django 3.1.12 on 2021-06-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('localized_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('country_full', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
    ]
